### ISSUE TITLE
Remove MariaDB after installation

### ISSUE THREAD

**Issue by melissajenner22** [AcroMedia/ansible-role-mariadb#4]
Hi,

I plan to install MariaDB server version 10.1.44-MariaDB-0ubuntu0.18.04.1. I have a few questions

1. How to specify above version in defaults/main.yml?
2. How to remove MariaDB after I installed it?
3. If there is no way to uninstall, how to upgrade MariaDB from 10.1 to 10.2?

Thank you.

**Comment by dale-c-anderson** [comment]
@melissajenner22 
1) If I'm not mistaken, Mariadb 10.1 is the default version on ubuntu 18.04, you shouldn't need to modify anything. If you need something newer, please [gain an understanding off the process first](https://www.linuxbabe.com/mariadb/install-mariadb-ubuntu-18-04-18-10 ), and then look inside this role's [tasks/main.yml](https://github.com/AcroMedia/ansible-role-mariadb/blob/12b79991058ad472d26d5436053358033b3816c4/tasks/main.yml#L34) to see how the variables from [defaults/main.yml](https://github.com/AcroMedia/ansible-role-mariadb/blob/12b79991058ad472d26d5436053358033b3816c4/defaults/main.yml#L31) are used.
2) As with the majority of published ansible roles, this one does not remove what it was designed to install. If you want to uninstall a service, you need to take care of that manually, write your own ansible tasks for it, or modify the role to support your desired behaviour. Here's a [stack exchange](https://serverfault.com/a/612125/41284) answer that illustrates the concept.
3) MariaDB publishes steps for upgrading through versions on their website: https://mariadb.com/kb/en/upgrading-from-mariadb-101-to-mariadb-102/
